"use client"

import "../css/main.css";
import Navbar from "../components/navbar";
import Footer from "../components/footer";
import "tw-elements/css/tw-elements.min.css";
import { useEffect } from "react";

import storeData from "../storeData/storeData";
import VerifyToken from "../lib/verifyToken";

// export const metadata = {
//   title: 'Next.js DSP',
//   description: 'Generated by Next.js',
// }
const title = 'Next.js DSP';
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const { userMno, userName, userGrade, setUserMno, setUserName, setUserGrade } = storeData();

  useEffect(()=>{

    //로그인 데이터 체크 
    if(userMno===0){
      const token = localStorage.getItem('authToken');
      if(token){
        try{
          const v = VerifyToken(token);
          setUserMno(v.mno);
          setUserName(v.name);
          setUserGrade(v.grade);
        }catch(e){
          console.log(e);
          //활성화 실패시 토큰 유효기간 만료로 기존 토큰 삭제 
          localStorage.removeItem('authToken');
          if(location.pathname!='/login'){
            location.href='/login';
          }
        }
      }
    }

  },[]);
  
  return (
    <html lang="en">
      <head>
        <title>{title}</title>
      </head>
      <body>
        <div className="layout">
        <Navbar ></Navbar>
        <main className="content w-full flex justify-center">
        {children}
        </main>
        <Footer></Footer>
        </div>
      </body>
    </html>
  )
}
